---
name: "Examples"
on:  # yamllint disable-line rule:truthy
  - "pull_request"

jobs:
  check_examples:
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v2"
      - name: "Setup environment"
        uses: "networktocode/gh-action-setup-poetry-environment@v2"
      - name: "Generating Examples"
        run: "poetry run invoke tests"
      - name: "Checking for uncommitted changes"
        # This will return failure if there are any uncommitted changes
        run: "git diff --exit-code"
      - name: "Checking for new files/direcotories"
        run: |
          if [ $(git ls-files --other --exclude-standard | wc -l) -gt 0 ]; then
            git ls-files --other --exclude-standard
            exit 1;
          fi
